#!/usr/bin/env python3
"""
scripts/collect_metrics.py

Computes per-class performance metrics for all (task × MIL × normalisation × dataset)
combinations and joins pre-computed centroid distances, producing a tidy CSV with one
row per (mil, task, cls_id):

    mil, task, cls_id, cls_name, metric,
    none_tcga, none_cptac, mac_cptac,
    delta_n, rpd,
    prev_tcga, prev_cptac, delta_p,
    d_c, b_tilde,
    tcga_tubule ... cptac_pmn

Performance metrics are parsed from results/{task}_results.txt (generated by
predict_slides.py), which uses the correct model checkpoint:
    - ER, PR, HER2: PR-AUC per class (OvR)
    - PAM50:        F1 per class (OvR)

Prevalence (prev_tcga, prev_cptac) is computed from y_true in predictions.csv
(y_true values are correct regardless of which model generated the predictions).

Centroid distances d_c are read from pre-computed CSVs:
    results/patch_intersection_all/{task}/centroid_distances_all.csv
    The d_mean column (average across the three MIL models) is used.

Usage:
    python scripts/collect_metrics.py \\
        [--exp_dir experiments] \\
        [--results_dir results] \\
        [--dist_dir results/patch_intersection_all] \\
        [--output results/per_class_metrics.csv]
"""

import argparse
import glob
import re
from pathlib import Path

import numpy as np
import pandas as pd

# ── Label mappings ────────────────────────────────────────────────────────────

# Maps (task, cls_id) → label as it appears in annotation xlsx (case-insensitive match)
CLS_TO_ANNOT_LABEL = {
    ('er',    0): 'ER-Negative',
    ('er',    1): 'ER-Positive',
    ('erbb2', 0): 'HER2-negative',
    ('erbb2', 1): 'HER2-positive',
    ('pr',    0): 'PR-negative',
    ('pr',    1): 'PR-positive',
    ('pam50', 0): 'BASAL',
    ('pam50', 1): 'HER2-enriched',
    ('pam50', 2): 'LUMINAL-A',
    ('pam50', 3): 'LUMINAL-B',
    ('pam50', 4): 'NORMAL-like',
}

# Maps (task, cls_id) → label as it appears in bio_b_tilde.csv
CLS_TO_BTILDE_LABEL = {
    ('er',    0): 'ER-NEGATIVE',
    ('er',    1): 'ER-POSITIVE',
    ('erbb2', 0): 'HER2-NEGATIVE',
    ('erbb2', 1): 'HER2-POSITIVE',
    ('pr',    0): 'PR-NEGATIVE',
    ('pr',    1): 'PR-POSITIVE',
    ('pam50', 0): 'BASAL',
    ('pam50', 1): 'HER2-ENRICHED',
    ('pam50', 2): 'LUMINAL-A',
    ('pam50', 3): 'LUMINAL-B',
    ('pam50', 4): 'NORMAL-LIKE',
}

MORPH_COLS = ['ESTRUCTURA GLANDULAR', 'ATIPIA NUCLEAR', 'MITOSIS',
              'NECROSIS', 'INFILTRADO_LI', 'INFILTRADO_PMN']
MORPH_SHORT = ['tubule', 'nuclear', 'mitotic', 'necrosis', 'li', 'pmn']

# ── Constants ─────────────────────────────────────────────────────────────────

TASKS = ['er', 'erbb2', 'pr', 'pam50']

TASK_METRIC = {
    'er':    'pr_auc',
    'erbb2': 'pr_auc',
    'pr':    'pr_auc',
    'pam50': 'f1',
}

CLASS_LABELS = {
    'er':    {0: 'neg',   1: 'pos'},
    'erbb2': {0: 'neg',   1: 'pos'},
    'pr':    {0: 'neg',   1: 'pos'},
    'pam50': {0: 'Basal', 1: 'Her2', 2: 'LumA', 3: 'LumB', 4: 'Normal'},
}

MIL_MODELS = ['clam_mil_mb', 'dsmil', 'transmil']

NORM_IDX = {'macenko': '00000', 'none': '00001'}


# ── Parse metrics from _results.txt ───────────────────────────────────────────

def parse_results_file(filepath: Path, task: str) -> dict:
    """
    Parse {task}_results.txt produced by predict_slides.py.
    Returns {(mil, norm, dataset, cls_id): metric_value}.
    """
    metric = TASK_METRIC[task]

    with open(filepath, encoding='utf-8') as fh:
        lines = fh.readlines()

    data = {}
    current_mil     = None
    current_norm    = None
    current_dataset = None
    in_classif_rep  = False

    i = 0
    while i < len(lines):
        line = lines[i].rstrip()

        # MIL / Norm header
        m = re.match(r'MIL:\s+(\S+)\s+\|\s+Norm:\s+(\S+)', line)
        if m:
            current_mil     = m.group(1)
            current_norm    = m.group(2)
            current_dataset = None
            in_classif_rep  = False
            i += 1
            continue

        # Dataset header
        m = re.match(r'Dataset:\s+(\S+)\s+\|', line)
        if m:
            current_dataset = m.group(1).lower()
            in_classif_rep  = False
            i += 1
            continue

        # PR-AUC block
        if metric == 'pr_auc' and line.strip() == 'PR-AUC por clase:':
            i += 1
            while i < len(lines):
                m2 = re.match(r'\s+(\d+)\(\d+\):\s+([\d.]+)', lines[i])
                if m2:
                    cls_id = int(m2.group(1))
                    value  = float(m2.group(2))
                    data[(current_mil, current_norm, current_dataset, cls_id)] = value
                    i += 1
                else:
                    break
            continue

        # F1 from Classification Report
        if metric == 'f1':
            if 'Classification Report' in line:
                in_classif_rep = True
                i += 1
                continue

            if in_classif_rep:
                m2 = re.match(
                    r'\s+(\d+)\(\d+\)\s+([\d.]+)\s+([\d.]+)\s+([\d.]+)\s+\d+',
                    line)
                if m2:
                    cls_id = int(m2.group(1))
                    f1     = float(m2.group(4))
                    data[(current_mil, current_norm, current_dataset, cls_id)] = f1
                elif re.match(r'\s*accuracy\b', line):
                    in_classif_rep = False

        i += 1

    return data


# ── Prevalence from predictions.csv ───────────────────────────────────────────

def find_predictions_tcga(exp_dir: Path, task: str, mil: str) -> Path | None:
    idx = NORM_IDX['none']
    matches = glob.glob(str(
        exp_dir / f'brca_virchow2_test_{task}_{mil}' /
        'mil' / f'{idx}-256_128_none_virchow2_{mil}_*' / 'predictions.csv'))
    return Path(matches[0]) if matches else None


def find_predictions_cptac(exp_dir: Path, task: str, mil: str) -> Path | None:
    idx = NORM_IDX['none']
    matches = glob.glob(str(
        exp_dir / f'brca_virchow2_test_{task}_{mil}' /
        'mil_eval' / f'{idx}-256_128_none_virchow2_{mil}_*_cptac' /
        '00000-*' / 'predictions.csv'))
    return Path(matches[0]) if matches else None


def compute_prevalence(df: pd.DataFrame, task: str) -> dict:
    """Return {cls_id: fraction} for each class."""
    classes = sorted(CLASS_LABELS[task].keys())
    y_true = df['y_true'].astype(int).values
    n = len(y_true)
    return {c: float((y_true == c).sum() / n) for c in classes}


# ── B̃_c ──────────────────────────────────────────────────────────────────────

def load_b_tilde(results_dir: Path) -> dict[tuple[str, int], float]:
    """Read bio_b_tilde.csv → {(task, cls_id): b_tilde}."""
    csv = results_dir / 'bio_b_tilde.csv'
    if not csv.exists():
        print(f'[WARN] bio_b_tilde.csv not found: {csv}')
        return {}
    df = pd.read_csv(csv)
    reverse = {v: k for k, v in CLS_TO_BTILDE_LABEL.items()}
    result = {}
    for _, row in df.iterrows():
        key = reverse.get(row['cls'].upper())
        if key:
            result[key] = float(row['b_tilde'])
    return result


# ── Morphological means ───────────────────────────────────────────────────────

def load_morph_means(results_dir: Path) -> dict[tuple[str, int, str], list[float]]:
    """
    Read representative_images_annotation_mean_input.xlsx.
    Returns {(task, cls_id, cohort): [tubule, nuclear, mitotic, necrosis, li, pmn]}.
    """
    xlsx = results_dir / 'representative_images_annotation_mean_input.xlsx'
    if not xlsx.exists():
        print(f'[WARN] annotation xlsx not found: {xlsx}')
        return {}

    result = {}
    for cohort in ['TCGA', 'CPTAC']:
        df = pd.read_excel(xlsx, sheet_name=cohort)
        df['ETIQUETA'] = df['ETIQUETA'].str.strip()
        for (task, cls_id), lbl in CLS_TO_ANNOT_LABEL.items():
            sub = df[df['ETIQUETA'] == lbl][MORPH_COLS]
            if sub.empty:
                continue
            result[(task, cls_id, cohort.lower())] = sub.mean().tolist()
    return result


# ── Centroid distances ────────────────────────────────────────────────────────

def load_centroid_distances(dist_dir: Path) -> dict[tuple[str, int], float]:
    """
    Read pre-computed centroid distances from results/patch_intersection_all/.
    Returns {(task, cls_id): d_mean}.
    """
    dists = {}
    for task in TASKS:
        csv = dist_dir / task / 'centroid_distances_all.csv'
        if not csv.exists():
            print(f'[WARN] centroid distances not found: {csv}')
            continue
        df = pd.read_csv(csv)
        for _, row in df.iterrows():
            dists[(row['task'], int(row['class']))] = float(row['d_mean'])
    return dists


# ── Main ──────────────────────────────────────────────────────────────────────

def main(exp_dir: Path, results_dir: Path, dist_dir: Path, output: Path) -> None:
    centroid_dists = load_centroid_distances(dist_dir)
    b_tilde        = load_b_tilde(results_dir)
    morph_means    = load_morph_means(results_dir)
    records = []

    for task in TASKS:
        classes     = CLASS_LABELS[task]
        metric_name = TASK_METRIC[task]

        # Parse all metrics for this task from the results txt
        results_txt = results_dir / f'{task}_results.txt'
        if not results_txt.exists():
            print(f'[WARN] {results_txt} not found — skipping task {task}')
            continue
        task_data = parse_results_file(results_txt, task)

        for mil in MIL_MODELS:
            # Prevalence: y_true from predictions.csv (correct regardless of model)
            p_tcga  = find_predictions_tcga(exp_dir, task, mil)
            p_cptac = find_predictions_cptac(exp_dir, task, mil)

            prev_tcga, prev_cptac = {}, {}
            if p_tcga:
                try:
                    prev_tcga = compute_prevalence(pd.read_csv(p_tcga), task)
                except Exception as e:
                    print(f'[WARN] prevalence TCGA {task}/{mil}: {e}')
            else:
                print(f'[WARN] {task}/{mil}: predictions.csv not found for TCGA prevalence')

            if p_cptac:
                try:
                    prev_cptac = compute_prevalence(pd.read_csv(p_cptac), task)
                except Exception as e:
                    print(f'[WARN] prevalence CPTAC {task}/{mil}: {e}')
            else:
                print(f'[WARN] {task}/{mil}: predictions.csv not found for CPTAC prevalence')

            for cls_id, cls_name in classes.items():
                none_tcga  = task_data.get((mil, 'none',    'tcga',  cls_id), float('nan'))
                none_cptac = task_data.get((mil, 'none',    'cptac', cls_id), float('nan'))
                mac_cptac  = task_data.get((mil, 'macenko', 'cptac', cls_id), float('nan'))

                delta_n = mac_cptac - none_cptac
                rpd = ((none_cptac - none_tcga) / (-none_tcga)
                       if none_tcga != 0 else float('nan'))

                pt = prev_tcga.get(cls_id,  float('nan'))
                pc = prev_cptac.get(cls_id, float('nan'))

                tcga_morph  = morph_means.get((task, cls_id, 'tcga'),  [float('nan')] * 6)
                cptac_morph = morph_means.get((task, cls_id, 'cptac'), [float('nan')] * 6)

                row = {
                    'mil':        mil,
                    'task':       task,
                    'cls_id':     cls_id,
                    'cls_name':   cls_name,
                    'metric':     metric_name,
                    'none_tcga':  round(none_tcga,  4),
                    'none_cptac': round(none_cptac, 4),
                    'mac_cptac':  round(mac_cptac,  4),
                    'delta_n':    round(delta_n,    4),
                    'rpd':        round(rpd,        4),
                    'prev_tcga':  round(pt,         4),
                    'prev_cptac': round(pc,         4),
                    'delta_p':    round(pc - pt,    4),
                    'd_c':        centroid_dists.get((task, cls_id), float('nan')),
                    'b_tilde':    b_tilde.get((task, cls_id), float('nan')),
                }
                for idx_m, col in enumerate(MORPH_SHORT):
                    row[f'tcga_{col}']  = (round(tcga_morph[idx_m],  3)
                                           if not np.isnan(tcga_morph[idx_m])  else float('nan'))
                    row[f'cptac_{col}'] = (round(cptac_morph[idx_m], 3)
                                           if not np.isnan(cptac_morph[idx_m]) else float('nan'))

                records.append(row)

    df_out = pd.DataFrame(records)
    output.parent.mkdir(parents=True, exist_ok=True)
    df_out.to_csv(output, index=False)
    print(f'Saved {len(df_out)} rows → {output}')
    print(df_out.to_string(index=False))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Collect per-class metrics and join pre-computed centroid distances.')
    parser.add_argument('--exp_dir', default='experiments',
                        help='Base experiments directory (default: experiments)')
    parser.add_argument('--results_dir', default='results',
                        help='Results directory with {task}_results.txt, bio_b_tilde.csv, '
                             'and annotation xlsx (default: results)')
    parser.add_argument('--dist_dir', default='results/patch_intersection_all_cosine',
                        help='Directory with centroid_distances_all.csv per task '
                             '(default: results/patch_intersection_all)')
    parser.add_argument('--output', default='results/per_class_metrics.csv',
                        help='Output CSV path (default: results/per_class_metrics.csv)')
    args = parser.parse_args()

    main(Path(args.exp_dir), Path(args.results_dir), Path(args.dist_dir), Path(args.output))